on: push
jobs:
  build_win:
   runs-on: windows-2019
   name: Build for Windows
   steps:
      - uses: actions/checkout@v2
      - run: "build/build.bat"
  build_linux:
    runs-on: ubuntu-latest
    name: Build For Linux
    steps:
      - uses: actions/checkout@v2 
      - run: chmod +X build/build.sh
      - run: ./build/build.sh
    
  upload:
    needs: [build_win, build_linux]
    runs-on: windows-2019
    name: Upload Artifact
    steps:
      - uses: actions/upload-artifact@v2
        with:
          name: Blaze_Cli
          path: bin/
